query Perfil {
  perfil{
    

        id
       telefone
    senha
    name
    idade
    genero
    email
    cidade
    SobreNome
 profissional{
     identificacaoProfissionalId
     id
    ambiente
    especial
    especialidade
    grupo
    servico
    idade
    imagens
    localatendimento
    qualificacao
    raio
      comentario_post {
        coteudo
        nota
      id
        notificacao_comentario {
          comentario
          id
          imgem_perfil
          cliente {
            id
          }
        }
      }
    }
    
      cliente {
      id
      nivel
    medicamentos
    }
 imgem_perfis {
      id
    imagen
    }

  }
}